import type { Article } from '@/types'

export function getMockArticles(): Article[] {
  const now = new Date()
  const sources = [
    { name: 'OpenAI', url: 'https://openai.com' },
    { name: 'Anthropic', url: 'https://anthropic.com' },
    { name: 'Google DeepMind', url: 'https://deepmind.google' },
    { name: 'TechCrunch AI', url: 'https://techcrunch.com' },
    { name: 'VentureBeat AI', url: 'https://venturebeat.com' },
    { name: 'MIT Tech Review', url: 'https://technologyreview.com' },
    { name: 'Hugging Face', url: 'https://huggingface.co' },
    { name: 'The Verge', url: 'https://theverge.com' },
    { name: 'NVIDIA Blog', url: 'https://blogs.nvidia.com' },
  ]

  const articles: Omit<Article, 'id'>[] = [
    {
      slug: 'gpt-5-launches-multimodal-reasoning',
      title: 'GPT-5 Launches with Unprecedented Multimodal Reasoning',
      punchyTitle: 'GPT-5 Redefines AI Reasoning Benchmarks',
      originalUrl: 'https://openai.com/blog/gpt-5',
      source: sources[0],
      author: 'OpenAI Team',
      publishedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
      summary: 'OpenAI has released GPT-5, featuring dramatic improvements in multimodal reasoning, code generation, and scientific problem-solving across all major benchmarks.',
      punchySummary: 'GPT-5 sets new records on every major AI benchmark, with 3× improvement in complex reasoning tasks and native video understanding capabilities.',
      keyInsights: ['3× improvement in multi-step reasoning over GPT-4o', 'Native video understanding without separate model', 'Reduced hallucination rate by 40% on factual queries', 'Available via API immediately, ChatGPT rollout in 2 weeks'],
      powerQuote: 'GPT-5 scores 87% on the hardest subset of MMLU — 15 points above the previous SOTA.',
      tldr: 'OpenAI launches GPT-5 with groundbreaking multimodal reasoning, outperforming all existing models across 50+ benchmarks.',
      whyItMatters: 'This shifts the competitive landscape significantly, potentially obsoleting many specialized AI tools built on GPT-4.',
      developerImpact: 'API pricing drops 60% vs GPT-4o for equivalent capability — major cost reduction for production deployments.',
      businessImpact: 'Enterprise GPT-5 tier includes 1M context window and custom fine-tuning — directly competes with Claude and Gemini enterprise offerings.',
      impactScore: 97,
      metaTitle: 'GPT-5 Launches with Multimodal Reasoning | AI Pulse',
      metaDescription: 'OpenAI releases GPT-5 with 3× reasoning improvements, native video understanding, and 40% lower hallucination rates. Full analysis.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['gpt-5', 'openai', 'llm', 'multimodal'],
      trendingScore: 98,
      isNew: true, isTrending: true, isHot: true,
      viewCount: 45200, shareCount: 8900,
      createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    },
    {
      slug: 'claude-4-anthropic-constitutional-ai',
      title: 'Anthropic Releases Claude 4 with Constitutional AI 2.0',
      punchyTitle: 'Claude 4 Sets New Bar for Safe, Capable AI',
      originalUrl: 'https://anthropic.com/news/claude-4',
      source: sources[1],
      author: 'Anthropic',
      publishedAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
      summary: 'Anthropic releases Claude 4 featuring Constitutional AI 2.0, dramatically improved coding abilities, and a 500K token context window.',
      punchySummary: 'Claude 4 surpasses GPT-4o on coding benchmarks with Constitutional AI 2.0 ensuring safer outputs and a 500K context window for entire codebases.',
      keyInsights: ['500K context window — processes entire codebases in one shot', 'Tops SWE-bench at 72% — highest coding score ever', 'Constitutional AI 2.0 reduces harmful outputs by 60%', 'API available now, Sonnet and Haiku variants coming Q3'],
      powerQuote: 'Claude 4 Sonnet scores 72% on SWE-bench, resolving more real-world GitHub issues than any model before it.',
      tldr: 'Claude 4 launches with 500K context, top coding performance, and Constitutional AI 2.0 for safer deployments.',
      whyItMatters: 'Enterprises can now process entire large codebases in a single prompt, fundamentally changing how AI assists in complex software projects.',
      developerImpact: '500K context enables full-repo refactoring and debugging — no more chunking strategies needed.',
      businessImpact: 'Constitutional AI 2.0 makes Claude 4 the compliance-friendly choice for regulated industries.',
      impactScore: 93,
      metaTitle: 'Claude 4 Launches: 500K Context + Constitutional AI 2.0 | AI Pulse',
      metaDescription: 'Anthropic releases Claude 4 with industry-leading 500K token context, 72% SWE-bench score, and Constitutional AI 2.0. Complete breakdown.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['claude', 'anthropic', 'llm', 'coding'],
      trendingScore: 91,
      isNew: true, isTrending: true, isHot: false,
      viewCount: 32100, shareCount: 5600,
      createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
    },
    {
      slug: 'nvidia-blackwell-gb300-ai-inference',
      title: 'NVIDIA GB300 Blackwell Ultra Ships: 30× Inference Speedup',
      punchyTitle: 'NVIDIA\'s GB300 Delivers 30× AI Inference Boost',
      originalUrl: 'https://blogs.nvidia.com/gb300',
      source: sources[8],
      author: 'NVIDIA',
      publishedAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
      summary: 'NVIDIA begins shipping GB300 Blackwell Ultra GPUs with 30× inference performance improvement over H100, featuring 288GB HBM3e memory.',
      punchySummary: 'The GB300 ships with 288GB HBM3e and 30× inference speedup over H100, enabling real-time LLM inference at GPT-4 scale for under $2/hour.',
      keyInsights: ['30× inference throughput vs H100 for LLM workloads', '288GB HBM3e with 8TB/s memory bandwidth', 'NVLink 5 enables 900GB/s GPU-to-GPU bandwidth', 'Cloud pricing expected at $1.50–2.00/hour vs $3+ for H100'],
      powerQuote: 'The GB300 enables GPT-4 class inference at 10× lower cost than H100-based systems.',
      tldr: 'NVIDIA GB300 ships with 30× LLM inference speedup and 288GB memory, dramatically cutting AI inference costs.',
      whyItMatters: 'This makes frontier model inference affordable for mid-market companies, potentially disrupting the current API pricing landscape.',
      developerImpact: 'Self-hosted frontier model inference becomes economically viable for teams with moderate traffic.',
      businessImpact: 'Cloud inference costs for LLM APIs could drop 60-80% as providers transition to GB300 infrastructure.',
      impactScore: 88,
      metaTitle: 'NVIDIA GB300 Ships: 30× AI Inference Speedup | AI Pulse',
      metaDescription: 'NVIDIA\'s Blackwell Ultra GB300 delivers 30× inference throughput vs H100 with 288GB HBM3e. Cost and performance analysis.',
      ogImageUrl: null,
      category: 'chips',
      tags: ['nvidia', 'blackwell', 'gpu', 'inference'],
      trendingScore: 85,
      isNew: true, isTrending: true, isHot: false,
      viewCount: 28400, shareCount: 4200,
      createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    },
    {
      slug: 'google-gemini-25-pro-vision',
      title: 'Google Gemini 2.5 Pro Achieves Human-Level Video Understanding',
      punchyTitle: 'Gemini 2.5 Pro Matches Human Video Comprehension',
      originalUrl: 'https://deepmind.google/blog/gemini-25-pro',
      source: sources[2],
      author: 'Google DeepMind',
      publishedAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
      summary: 'Google DeepMind releases Gemini 2.5 Pro with human-level video understanding benchmarks and a 2M token context window supporting full-length films.',
      punchySummary: 'Gemini 2.5 Pro achieves 94.3% on video QA benchmarks (human baseline: 96%) with a 2M token context processing 2-hour films in full.',
      keyInsights: ['2M token context window — processes 2-hour films, entire codebases', 'Human-level video understanding at 94.3% on VideoMME', 'Native audio, image, video, and code in single model', '50% cost reduction vs Gemini 1.5 Pro at same quality'],
      powerQuote: '2M context is not just a number — it means the model can reason over your entire product codebase simultaneously.',
      tldr: 'Gemini 2.5 Pro reaches near-human video comprehension with a 2M token context, making it the most capable multimodal model for long-context tasks.',
      whyItMatters: 'A 2M context window changes how enterprises can use AI for document analysis, long video processing, and complex code review.',
      developerImpact: 'RAG architectures for large codebases become unnecessary — just pass the entire codebase directly.',
      businessImpact: 'Media and content companies gain a powerful tool for automated video analysis, clipping, and cataloging.',
      impactScore: 85,
      metaTitle: 'Gemini 2.5 Pro: Human-Level Video + 2M Context | AI Pulse',
      metaDescription: 'Google releases Gemini 2.5 Pro with 2M token context and human-level video understanding. Technical breakdown and implications.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['gemini', 'google', 'multimodal', 'video'],
      trendingScore: 82,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 22100, shareCount: 3800,
      createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    },
    {
      slug: 'meta-llama-4-open-source-release',
      title: 'Meta Releases Llama 4: Open-Source GPT-4 Competitor',
      punchyTitle: 'Llama 4 Closes the Gap with Proprietary AI Giants',
      originalUrl: 'https://ai.meta.com/blog/llama-4',
      source: { name: 'Meta AI', url: 'https://ai.meta.com' },
      author: 'Meta AI',
      publishedAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
      summary: 'Meta releases Llama 4 under an open-source license, matching GPT-4o on most benchmarks and setting a new standard for open-source AI.',
      punchySummary: 'Llama 4 matches GPT-4o on 8 of 10 major benchmarks while being fully open-source and runnable on consumer hardware with 4-bit quantization.',
      keyInsights: ['Matches GPT-4o on MMLU, HumanEval, and GSM8K', 'Runs on consumer RTX 4090 with 4-bit quantization', 'Apache 2.0 license — fully commercial use allowed', 'Fine-tuned variants for code, math, and instruct available day one'],
      powerQuote: 'With Llama 4, open-source AI has definitively caught up to the frontier.',
      tldr: 'Meta\'s Llama 4 matches proprietary frontier models on key benchmarks while remaining fully open-source under Apache 2.0.',
      whyItMatters: 'Open-source frontier AI eliminates vendor lock-in for enterprises and empowers researchers globally without API costs.',
      developerImpact: 'Self-hosted frontier AI becomes practical — eliminate $0.01/1K token costs for high-volume applications.',
      businessImpact: 'Companies can now deploy GPT-4 class models on-premise, resolving data privacy concerns for sensitive deployments.',
      impactScore: 91,
      metaTitle: 'Meta Llama 4: Open-Source GPT-4 Competitor Released | AI Pulse',
      metaDescription: 'Meta releases Llama 4 matching GPT-4o benchmarks under Apache 2.0. Full breakdown of capabilities, hardware requirements, and implications.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['llama', 'meta', 'open-source', 'llm'],
      trendingScore: 88,
      isNew: false, isTrending: true, isHot: true,
      viewCount: 35600, shareCount: 7200,
      createdAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
    },
    {
      slug: 'eu-ai-act-enforcement-begins',
      title: 'EU AI Act Enforcement Begins: What Companies Must Do Now',
      punchyTitle: 'EU AI Act Goes Live: Compliance Deadlines Hit',
      originalUrl: 'https://techcrunch.com/2026/01/eu-ai-act-enforcement',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
      summary: 'The EU AI Act enters enforcement phase, requiring high-risk AI system operators to complete conformity assessments or face fines up to 6% of global revenue.',
      punchySummary: 'High-risk AI systems must now have documented risk assessments, human oversight mechanisms, and data governance logs — or face fines up to €35M or 6% of global revenue.',
      keyInsights: ['High-risk AI systems must complete conformity assessment by Aug 2026', 'Fines up to €35M or 6% global revenue for non-compliance', 'Prohibited AI practices (social scoring, subliminal manipulation) banned immediately', 'GPAI model providers must publish technical documentation'],
      powerQuote: 'The EU AI Act is the world\'s first comprehensive AI regulation — every global company deploying AI in Europe is now affected.',
      tldr: 'EU AI Act enforcement begins, requiring high-risk AI compliance assessments with penalties up to 6% of global revenue.',
      whyItMatters: 'Any company deploying AI systems in Europe — regardless of HQ location — now faces binding legal requirements and potential 8-figure fines.',
      developerImpact: 'AI systems in hiring, credit scoring, medical devices, and critical infrastructure require formal risk documentation and audit trails.',
      businessImpact: 'Legal and compliance teams need immediate audits of all AI deployments touching EU customers.',
      impactScore: 79,
      metaTitle: 'EU AI Act Enforcement: What Companies Must Do Now | AI Pulse',
      metaDescription: 'EU AI Act enters enforcement phase. High-risk AI systems face conformity requirements. Full compliance guide for businesses.',
      ogImageUrl: null,
      category: 'regulation',
      tags: ['eu', 'regulation', 'compliance', 'ai-act'],
      trendingScore: 76,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 18900, shareCount: 3100,
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    },
    {
      slug: 'openai-o3-reasoning-model-benchmark',
      title: 'OpenAI o3 Achieves 96% on AIME, Near-Perfect Math Reasoning',
      punchyTitle: 'o3 Solves 96% of Olympiad Math Problems',
      originalUrl: 'https://openai.com/blog/o3',
      source: sources[0],
      author: 'OpenAI',
      publishedAt: new Date(now.getTime() - 30 * 60 * 60 * 1000),
      summary: 'OpenAI\'s o3 reasoning model achieves 96.7% on AIME and 87.5% on FrontierMath, establishing a new frontier in mathematical and logical reasoning.',
      punchySummary: 'o3 scores 96.7% on competition math (AIME) — previously 83% was state-of-art — and solves 87.5% of FrontierMath problems designed to be unsolvable by current AI.',
      keyInsights: ['96.7% on AIME (vs 83% previous SOTA)', '87.5% on FrontierMath (estimated <2% for prior models)', 'Achieves 86% on ARC-AGI-2 benchmark', 'Uses extended compute-time reasoning — scalable inference compute'],
      powerQuote: 'o3 doesn\'t just solve math problems — it finds novel approaches that human mathematicians hadn\'t considered.',
      tldr: 'OpenAI o3 sets new math reasoning SOTA with 96.7% AIME score, suggesting compute-time scaling continues to yield major gains.',
      whyItMatters: 'Demonstrates that reasoning capability continues to scale with inference compute, potentially unlocking scientific discovery applications.',
      developerImpact: 'Complex algorithmic problems and proof verification become tractable with o3 — major upgrade for theorem proving tools.',
      businessImpact: 'Financial modeling, risk analysis, and quantitative research applications gain access to near-PhD-level mathematical reasoning.',
      impactScore: 92,
      metaTitle: 'OpenAI o3: 96% AIME Score, Near-Perfect Math Reasoning | AI Pulse',
      metaDescription: 'OpenAI o3 achieves 96.7% on AIME competition math, 87.5% on FrontierMath. Analysis of compute-time reasoning scaling.',
      ogImageUrl: null,
      category: 'research',
      tags: ['o3', 'openai', 'reasoning', 'math'],
      trendingScore: 86,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 29700, shareCount: 5900,
      createdAt: new Date(now.getTime() - 30 * 60 * 60 * 1000),
    },
    {
      slug: 'anthropic-computer-use-agents',
      title: 'Anthropic\'s Computer Use API Enables Autonomous Coding Agents',
      punchyTitle: 'Claude Now Controls Your Computer to Write Code',
      originalUrl: 'https://anthropic.com/news/computer-use-ga',
      source: sources[1],
      author: 'Anthropic',
      publishedAt: new Date(now.getTime() - 36 * 60 * 60 * 1000),
      summary: 'Anthropic releases Computer Use API for general availability, enabling Claude to autonomously interact with desktop applications, browsers, and terminals.',
      punchySummary: 'Claude\'s Computer Use exits beta — it can now run full software development workflows: reading docs, writing code, running tests, and fixing bugs autonomously.',
      keyInsights: ['GA release with 99.9% uptime SLA', 'Completes 73% of SWE-bench real-world tasks autonomously', 'Integrates with VS Code, GitHub Actions, Cursor natively', 'Audit log and human-in-the-loop controls for enterprise safety'],
      powerQuote: 'Computer Use isn\'t about replacing developers — it\'s about giving every developer a 24/7 autonomous coding partner.',
      tldr: 'Claude Computer Use GA enables fully autonomous software development workflows with 73% SWE-bench task completion.',
      whyItMatters: 'Autonomous coding agents that can run tests, read error logs, and iterate without human intervention represent a step-change in developer productivity.',
      developerImpact: 'Repetitive DevOps tasks, dependency updates, and test writing can now be delegated to autonomous Claude agents.',
      businessImpact: 'Engineering team capacity effectively increases — one developer can supervise multiple autonomous agents working in parallel.',
      impactScore: 87,
      metaTitle: 'Anthropic Computer Use GA: Autonomous AI Coding Agents | AI Pulse',
      metaDescription: 'Anthropic releases Computer Use API for GA. Claude autonomously handles full development workflows with 73% SWE-bench success.',
      ogImageUrl: null,
      category: 'agents',
      tags: ['computer-use', 'anthropic', 'agents', 'coding'],
      trendingScore: 83,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 24300, shareCount: 4700,
      createdAt: new Date(now.getTime() - 36 * 60 * 60 * 1000),
    },
    {
      slug: 'figure-humanoid-robot-openai-integration',
      title: 'Figure 02 Humanoid Robot Achieves 95% Factory Task Success Rate',
      punchyTitle: 'Figure\'s Robot Masters Factory Work at Near-Human Rates',
      originalUrl: 'https://venturebeat.com/ai/figure-02-factory',
      source: sources[4],
      author: 'VentureBeat',
      publishedAt: new Date(now.getTime() - 42 * 60 * 60 * 1000),
      summary: 'Figure\'s Figure 02 humanoid robot, powered by a custom VLA model trained on GPT-4o, achieves 95% success rate on BMW factory assembly tasks.',
      punchySummary: 'Figure 02 achieves 95% task success in BMW\'s Spartanburg factory using a Vision-Language-Action model — 4× improvement over the previous generation in 8 months.',
      keyInsights: ['95% task success on automotive assembly (up from 24% in 2024)', 'Powered by custom VLA model built on GPT-4o vision', 'Deployed in BMW Spartanburg with 40 units operational', 'Learning new tasks in hours via imitation learning from video'],
      powerQuote: 'Figure 02 is the first commercially deployed humanoid to achieve near-human task success rates in an unstructured industrial environment.',
      tldr: 'Figure 02 achieves 95% factory task success with GPT-4o-powered VLA model, marking robotics\' first commercial-scale humanoid deployment.',
      whyItMatters: 'Crossing 95% success rate in real factory conditions marks the inflection point where humanoid robots become economically viable vs human labor.',
      developerImpact: 'Figure\'s VLA architecture and training pipeline papers expected to unlock similar capabilities for research teams.',
      businessImpact: 'Manufacturing sector faces near-term automation wave — BMW partnership signals enterprise validation of humanoid ROI.',
      impactScore: 84,
      metaTitle: 'Figure 02 Achieves 95% Factory Task Success with OpenAI | AI Pulse',
      metaDescription: 'Figure\'s humanoid robot hits 95% assembly task success at BMW using GPT-4o-powered VLA model. Robotics inflection point analysis.',
      ogImageUrl: null,
      category: 'robotics',
      tags: ['robotics', 'figure', 'humanoid', 'manufacturing'],
      trendingScore: 78,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 19800, shareCount: 3600,
      createdAt: new Date(now.getTime() - 42 * 60 * 60 * 1000),
    },
    {
      slug: 'mistral-codestral-code-model',
      title: 'Mistral Releases Codestral 2.0: Fastest Code Model at GPT-4 Quality',
      punchyTitle: 'Codestral 2.0: GPT-4 Coding Quality at 10× Speed',
      originalUrl: 'https://mistral.ai/news/codestral-2',
      source: { name: 'Mistral AI', url: 'https://mistral.ai' },
      author: 'Mistral AI',
      publishedAt: new Date(now.getTime() - 50 * 60 * 60 * 1000),
      summary: 'Mistral releases Codestral 2.0 with GPT-4 level HumanEval scores at 10× faster inference speed, targeting production coding assistant deployments.',
      punchySummary: 'Codestral 2.0 matches GPT-4o on HumanEval (86%) while running at 2,000+ tokens/sec — making real-time code completion economically viable at scale.',
      keyInsights: ['86% on HumanEval — matches GPT-4o', '2,000+ tokens/sec on standard hardware', 'FIM (fill-in-middle) optimized for IDE autocomplete', 'Apache 2.0 — self-hostable without licensing fees'],
      powerQuote: 'Codestral 2.0 makes real-time, frontier-quality code completion economically viable for teams of any size.',
      tldr: 'Codestral 2.0 matches GPT-4 coding quality at 10× inference speed, enabling real-time AI autocomplete at production scale.',
      whyItMatters: 'The speed gap between open and proprietary models closes — teams can now self-host GPT-4 quality code completion.',
      developerImpact: 'Real-time FIM completion at GPT-4 quality eliminates the tradeoff between latency and capability in AI code editors.',
      businessImpact: null,
      impactScore: 78,
      metaTitle: 'Codestral 2.0: GPT-4 Code Quality at 10× Speed | AI Pulse',
      metaDescription: 'Mistral releases Codestral 2.0 matching GPT-4o HumanEval at 2000+ tokens/sec. Open-source code model analysis.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['mistral', 'codestral', 'coding', 'open-source'],
      trendingScore: 72,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 15600, shareCount: 2800,
      createdAt: new Date(now.getTime() - 50 * 60 * 60 * 1000),
    },
  ]

  return articles.map((a, i) => ({ ...a, id: `mock-${i + 1}` })) as Article[]
}
