import type { Article } from '@/types'

export function getMockArticles(): Article[] {
  const now = new Date()
  const sources = [
    { name: 'OpenAI', url: 'https://openai.com' },
    { name: 'Anthropic', url: 'https://anthropic.com' },
    { name: 'Google DeepMind', url: 'https://deepmind.google' },
    { name: 'TechCrunch AI', url: 'https://techcrunch.com' },
    { name: 'VentureBeat AI', url: 'https://venturebeat.com' },
    { name: 'MIT Tech Review', url: 'https://technologyreview.com' },
    { name: 'Hugging Face', url: 'https://huggingface.co' },
    { name: 'The Verge', url: 'https://theverge.com' },
    { name: 'NVIDIA Blog', url: 'https://blogs.nvidia.com' },
  ]

  const articles: Omit<Article, 'id'>[] = [
    {
      slug: 'gpt-5-launches-multimodal-reasoning',
      title: 'GPT-5 Launches with Unprecedented Multimodal Reasoning',
      punchyTitle: 'GPT-5 Redefines AI Reasoning Benchmarks',
      originalUrl: 'https://openai.com/blog/gpt-5',
      source: sources[0],
      author: 'OpenAI Team',
      publishedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
      summary: 'OpenAI has released GPT-5, featuring dramatic improvements in multimodal reasoning, code generation, and scientific problem-solving across all major benchmarks.',
      punchySummary: 'GPT-5 sets new records on every major AI benchmark, with 3× improvement in complex reasoning tasks and native video understanding capabilities.',
      keyInsights: ['3× improvement in multi-step reasoning over GPT-4o', 'Native video understanding without separate model', 'Reduced hallucination rate by 40% on factual queries', 'Available via API immediately, ChatGPT rollout in 2 weeks'],
      powerQuote: 'GPT-5 scores 87% on the hardest subset of MMLU — 15 points above the previous SOTA.',
      tldr: 'OpenAI launches GPT-5 with groundbreaking multimodal reasoning, outperforming all existing models across 50+ benchmarks.',
      whyItMatters: 'This shifts the competitive landscape significantly, potentially obsoleting many specialized AI tools built on GPT-4.',
      developerImpact: 'API pricing drops 60% vs GPT-4o for equivalent capability — major cost reduction for production deployments.',
      businessImpact: 'Enterprise GPT-5 tier includes 1M context window and custom fine-tuning — directly competes with Claude and Gemini enterprise offerings.',
      impactScore: 97,
      metaTitle: 'GPT-5 Launches with Multimodal Reasoning | AI Pulse',
      metaDescription: 'OpenAI releases GPT-5 with 3× reasoning improvements, native video understanding, and 40% lower hallucination rates. Full analysis.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['gpt-5', 'openai', 'llm', 'multimodal'],
      trendingScore: 98,
      isNew: true, isTrending: true, isHot: true,
      viewCount: 45200, shareCount: 8900,
      createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    },
    {
      slug: 'claude-4-anthropic-constitutional-ai',
      title: 'Anthropic Releases Claude 4 with Constitutional AI 2.0',
      punchyTitle: 'Claude 4 Sets New Bar for Safe, Capable AI',
      originalUrl: 'https://anthropic.com/news/claude-4',
      source: sources[1],
      author: 'Anthropic',
      publishedAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
      summary: 'Anthropic releases Claude 4 featuring Constitutional AI 2.0, dramatically improved coding abilities, and a 500K token context window.',
      punchySummary: 'Claude 4 surpasses GPT-4o on coding benchmarks with Constitutional AI 2.0 ensuring safer outputs and a 500K context window for entire codebases.',
      keyInsights: ['500K context window — processes entire codebases in one shot', 'Tops SWE-bench at 72% — highest coding score ever', 'Constitutional AI 2.0 reduces harmful outputs by 60%', 'API available now, Sonnet and Haiku variants coming Q3'],
      powerQuote: 'Claude 4 Sonnet scores 72% on SWE-bench, resolving more real-world GitHub issues than any model before it.',
      tldr: 'Claude 4 launches with 500K context, top coding performance, and Constitutional AI 2.0 for safer deployments.',
      whyItMatters: 'Enterprises can now process entire large codebases in a single prompt, fundamentally changing how AI assists in complex software projects.',
      developerImpact: '500K context enables full-repo refactoring and debugging — no more chunking strategies needed.',
      businessImpact: 'Constitutional AI 2.0 makes Claude 4 the compliance-friendly choice for regulated industries.',
      impactScore: 93,
      metaTitle: 'Claude 4 Launches: 500K Context + Constitutional AI 2.0 | AI Pulse',
      metaDescription: 'Anthropic releases Claude 4 with industry-leading 500K token context, 72% SWE-bench score, and Constitutional AI 2.0. Complete breakdown.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['claude', 'anthropic', 'llm', 'coding'],
      trendingScore: 91,
      isNew: true, isTrending: true, isHot: false,
      viewCount: 32100, shareCount: 5600,
      createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
    },
    {
      slug: 'nvidia-blackwell-gb300-ai-inference',
      title: 'NVIDIA GB300 Blackwell Ultra Ships: 30× Inference Speedup',
      punchyTitle: 'NVIDIA\'s GB300 Delivers 30× AI Inference Boost',
      originalUrl: 'https://blogs.nvidia.com/gb300',
      source: sources[8],
      author: 'NVIDIA',
      publishedAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
      summary: 'NVIDIA begins shipping GB300 Blackwell Ultra GPUs with 30× inference performance improvement over H100, featuring 288GB HBM3e memory.',
      punchySummary: 'The GB300 ships with 288GB HBM3e and 30× inference speedup over H100, enabling real-time LLM inference at GPT-4 scale for under $2/hour.',
      keyInsights: ['30× inference throughput vs H100 for LLM workloads', '288GB HBM3e with 8TB/s memory bandwidth', 'NVLink 5 enables 900GB/s GPU-to-GPU bandwidth', 'Cloud pricing expected at $1.50–2.00/hour vs $3+ for H100'],
      powerQuote: 'The GB300 enables GPT-4 class inference at 10× lower cost than H100-based systems.',
      tldr: 'NVIDIA GB300 ships with 30× LLM inference speedup and 288GB memory, dramatically cutting AI inference costs.',
      whyItMatters: 'This makes frontier model inference affordable for mid-market companies, potentially disrupting the current API pricing landscape.',
      developerImpact: 'Self-hosted frontier model inference becomes economically viable for teams with moderate traffic.',
      businessImpact: 'Cloud inference costs for LLM APIs could drop 60-80% as providers transition to GB300 infrastructure.',
      impactScore: 88,
      metaTitle: 'NVIDIA GB300 Ships: 30× AI Inference Speedup | AI Pulse',
      metaDescription: 'NVIDIA\'s Blackwell Ultra GB300 delivers 30× inference throughput vs H100 with 288GB HBM3e. Cost and performance analysis.',
      ogImageUrl: null,
      category: 'chips',
      tags: ['nvidia', 'blackwell', 'gpu', 'inference'],
      trendingScore: 85,
      isNew: true, isTrending: true, isHot: false,
      viewCount: 28400, shareCount: 4200,
      createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    },
    {
      slug: 'google-gemini-25-pro-vision',
      title: 'Google Gemini 2.5 Pro Achieves Human-Level Video Understanding',
      punchyTitle: 'Gemini 2.5 Pro Matches Human Video Comprehension',
      originalUrl: 'https://deepmind.google/blog/gemini-25-pro',
      source: sources[2],
      author: 'Google DeepMind',
      publishedAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
      summary: 'Google DeepMind releases Gemini 2.5 Pro with human-level video understanding benchmarks and a 2M token context window supporting full-length films.',
      punchySummary: 'Gemini 2.5 Pro achieves 94.3% on video QA benchmarks (human baseline: 96%) with a 2M token context processing 2-hour films in full.',
      keyInsights: ['2M token context window — processes 2-hour films, entire codebases', 'Human-level video understanding at 94.3% on VideoMME', 'Native audio, image, video, and code in single model', '50% cost reduction vs Gemini 1.5 Pro at same quality'],
      powerQuote: '2M context is not just a number — it means the model can reason over your entire product codebase simultaneously.',
      tldr: 'Gemini 2.5 Pro reaches near-human video comprehension with a 2M token context, making it the most capable multimodal model for long-context tasks.',
      whyItMatters: 'A 2M context window changes how enterprises can use AI for document analysis, long video processing, and complex code review.',
      developerImpact: 'RAG architectures for large codebases become unnecessary — just pass the entire codebase directly.',
      businessImpact: 'Media and content companies gain a powerful tool for automated video analysis, clipping, and cataloging.',
      impactScore: 85,
      metaTitle: 'Gemini 2.5 Pro: Human-Level Video + 2M Context | AI Pulse',
      metaDescription: 'Google releases Gemini 2.5 Pro with 2M token context and human-level video understanding. Technical breakdown and implications.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['gemini', 'google', 'multimodal', 'video'],
      trendingScore: 82,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 22100, shareCount: 3800,
      createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    },
    {
      slug: 'meta-llama-4-open-source-release',
      title: 'Meta Releases Llama 4: Open-Source GPT-4 Competitor',
      punchyTitle: 'Llama 4 Closes the Gap with Proprietary AI Giants',
      originalUrl: 'https://ai.meta.com/blog/llama-4',
      source: { name: 'Meta AI', url: 'https://ai.meta.com' },
      author: 'Meta AI',
      publishedAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
      summary: 'Meta releases Llama 4 under an open-source license, matching GPT-4o on most benchmarks and setting a new standard for open-source AI.',
      punchySummary: 'Llama 4 matches GPT-4o on 8 of 10 major benchmarks while being fully open-source and runnable on consumer hardware with 4-bit quantization.',
      keyInsights: ['Matches GPT-4o on MMLU, HumanEval, and GSM8K', 'Runs on consumer RTX 4090 with 4-bit quantization', 'Apache 2.0 license — fully commercial use allowed', 'Fine-tuned variants for code, math, and instruct available day one'],
      powerQuote: 'With Llama 4, open-source AI has definitively caught up to the frontier.',
      tldr: 'Meta\'s Llama 4 matches proprietary frontier models on key benchmarks while remaining fully open-source under Apache 2.0.',
      whyItMatters: 'Open-source frontier AI eliminates vendor lock-in for enterprises and empowers researchers globally without API costs.',
      developerImpact: 'Self-hosted frontier AI becomes practical — eliminate $0.01/1K token costs for high-volume applications.',
      businessImpact: 'Companies can now deploy GPT-4 class models on-premise, resolving data privacy concerns for sensitive deployments.',
      impactScore: 91,
      metaTitle: 'Meta Llama 4: Open-Source GPT-4 Competitor Released | AI Pulse',
      metaDescription: 'Meta releases Llama 4 matching GPT-4o benchmarks under Apache 2.0. Full breakdown of capabilities, hardware requirements, and implications.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['llama', 'meta', 'open-source', 'llm'],
      trendingScore: 88,
      isNew: false, isTrending: true, isHot: true,
      viewCount: 35600, shareCount: 7200,
      createdAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
    },
    {
      slug: 'eu-ai-act-enforcement-begins',
      title: 'EU AI Act Enforcement Begins: What Companies Must Do Now',
      punchyTitle: 'EU AI Act Goes Live: Compliance Deadlines Hit',
      originalUrl: 'https://techcrunch.com/2026/01/eu-ai-act-enforcement',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
      summary: 'The EU AI Act enters enforcement phase, requiring high-risk AI system operators to complete conformity assessments or face fines up to 6% of global revenue.',
      punchySummary: 'High-risk AI systems must now have documented risk assessments, human oversight mechanisms, and data governance logs — or face fines up to €35M or 6% of global revenue.',
      keyInsights: ['High-risk AI systems must complete conformity assessment by Aug 2026', 'Fines up to €35M or 6% global revenue for non-compliance', 'Prohibited AI practices (social scoring, subliminal manipulation) banned immediately', 'GPAI model providers must publish technical documentation'],
      powerQuote: 'The EU AI Act is the world\'s first comprehensive AI regulation — every global company deploying AI in Europe is now affected.',
      tldr: 'EU AI Act enforcement begins, requiring high-risk AI compliance assessments with penalties up to 6% of global revenue.',
      whyItMatters: 'Any company deploying AI systems in Europe — regardless of HQ location — now faces binding legal requirements and potential 8-figure fines.',
      developerImpact: 'AI systems in hiring, credit scoring, medical devices, and critical infrastructure require formal risk documentation and audit trails.',
      businessImpact: 'Legal and compliance teams need immediate audits of all AI deployments touching EU customers.',
      impactScore: 79,
      metaTitle: 'EU AI Act Enforcement: What Companies Must Do Now | AI Pulse',
      metaDescription: 'EU AI Act enters enforcement phase. High-risk AI systems face conformity requirements. Full compliance guide for businesses.',
      ogImageUrl: null,
      category: 'regulation',
      tags: ['eu', 'regulation', 'compliance', 'ai-act'],
      trendingScore: 76,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 18900, shareCount: 3100,
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    },
    {
      slug: 'openai-o3-reasoning-model-benchmark',
      title: 'OpenAI o3 Achieves 96% on AIME, Near-Perfect Math Reasoning',
      punchyTitle: 'o3 Solves 96% of Olympiad Math Problems',
      originalUrl: 'https://openai.com/blog/o3',
      source: sources[0],
      author: 'OpenAI',
      publishedAt: new Date(now.getTime() - 30 * 60 * 60 * 1000),
      summary: 'OpenAI\'s o3 reasoning model achieves 96.7% on AIME and 87.5% on FrontierMath, establishing a new frontier in mathematical and logical reasoning.',
      punchySummary: 'o3 scores 96.7% on competition math (AIME) — previously 83% was state-of-art — and solves 87.5% of FrontierMath problems designed to be unsolvable by current AI.',
      keyInsights: ['96.7% on AIME (vs 83% previous SOTA)', '87.5% on FrontierMath (estimated <2% for prior models)', 'Achieves 86% on ARC-AGI-2 benchmark', 'Uses extended compute-time reasoning — scalable inference compute'],
      powerQuote: 'o3 doesn\'t just solve math problems — it finds novel approaches that human mathematicians hadn\'t considered.',
      tldr: 'OpenAI o3 sets new math reasoning SOTA with 96.7% AIME score, suggesting compute-time scaling continues to yield major gains.',
      whyItMatters: 'Demonstrates that reasoning capability continues to scale with inference compute, potentially unlocking scientific discovery applications.',
      developerImpact: 'Complex algorithmic problems and proof verification become tractable with o3 — major upgrade for theorem proving tools.',
      businessImpact: 'Financial modeling, risk analysis, and quantitative research applications gain access to near-PhD-level mathematical reasoning.',
      impactScore: 92,
      metaTitle: 'OpenAI o3: 96% AIME Score, Near-Perfect Math Reasoning | AI Pulse',
      metaDescription: 'OpenAI o3 achieves 96.7% on AIME competition math, 87.5% on FrontierMath. Analysis of compute-time reasoning scaling.',
      ogImageUrl: null,
      category: 'research',
      tags: ['o3', 'openai', 'reasoning', 'math'],
      trendingScore: 86,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 29700, shareCount: 5900,
      createdAt: new Date(now.getTime() - 30 * 60 * 60 * 1000),
    },
    {
      slug: 'anthropic-computer-use-agents',
      title: 'Anthropic\'s Computer Use API Enables Autonomous Coding Agents',
      punchyTitle: 'Claude Now Controls Your Computer to Write Code',
      originalUrl: 'https://anthropic.com/news/computer-use-ga',
      source: sources[1],
      author: 'Anthropic',
      publishedAt: new Date(now.getTime() - 36 * 60 * 60 * 1000),
      summary: 'Anthropic releases Computer Use API for general availability, enabling Claude to autonomously interact with desktop applications, browsers, and terminals.',
      punchySummary: 'Claude\'s Computer Use exits beta — it can now run full software development workflows: reading docs, writing code, running tests, and fixing bugs autonomously.',
      keyInsights: ['GA release with 99.9% uptime SLA', 'Completes 73% of SWE-bench real-world tasks autonomously', 'Integrates with VS Code, GitHub Actions, Cursor natively', 'Audit log and human-in-the-loop controls for enterprise safety'],
      powerQuote: 'Computer Use isn\'t about replacing developers — it\'s about giving every developer a 24/7 autonomous coding partner.',
      tldr: 'Claude Computer Use GA enables fully autonomous software development workflows with 73% SWE-bench task completion.',
      whyItMatters: 'Autonomous coding agents that can run tests, read error logs, and iterate without human intervention represent a step-change in developer productivity.',
      developerImpact: 'Repetitive DevOps tasks, dependency updates, and test writing can now be delegated to autonomous Claude agents.',
      businessImpact: 'Engineering team capacity effectively increases — one developer can supervise multiple autonomous agents working in parallel.',
      impactScore: 87,
      metaTitle: 'Anthropic Computer Use GA: Autonomous AI Coding Agents | AI Pulse',
      metaDescription: 'Anthropic releases Computer Use API for GA. Claude autonomously handles full development workflows with 73% SWE-bench success.',
      ogImageUrl: null,
      category: 'agents',
      tags: ['computer-use', 'anthropic', 'agents', 'coding'],
      trendingScore: 83,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 24300, shareCount: 4700,
      createdAt: new Date(now.getTime() - 36 * 60 * 60 * 1000),
    },
    {
      slug: 'figure-humanoid-robot-openai-integration',
      title: 'Figure 02 Humanoid Robot Achieves 95% Factory Task Success Rate',
      punchyTitle: 'Figure\'s Robot Masters Factory Work at Near-Human Rates',
      originalUrl: 'https://venturebeat.com/ai/figure-02-factory',
      source: sources[4],
      author: 'VentureBeat',
      publishedAt: new Date(now.getTime() - 42 * 60 * 60 * 1000),
      summary: 'Figure\'s Figure 02 humanoid robot, powered by a custom VLA model trained on GPT-4o, achieves 95% success rate on BMW factory assembly tasks.',
      punchySummary: 'Figure 02 achieves 95% task success in BMW\'s Spartanburg factory using a Vision-Language-Action model — 4× improvement over the previous generation in 8 months.',
      keyInsights: ['95% task success on automotive assembly (up from 24% in 2024)', 'Powered by custom VLA model built on GPT-4o vision', 'Deployed in BMW Spartanburg with 40 units operational', 'Learning new tasks in hours via imitation learning from video'],
      powerQuote: 'Figure 02 is the first commercially deployed humanoid to achieve near-human task success rates in an unstructured industrial environment.',
      tldr: 'Figure 02 achieves 95% factory task success with GPT-4o-powered VLA model, marking robotics\' first commercial-scale humanoid deployment.',
      whyItMatters: 'Crossing 95% success rate in real factory conditions marks the inflection point where humanoid robots become economically viable vs human labor.',
      developerImpact: 'Figure\'s VLA architecture and training pipeline papers expected to unlock similar capabilities for research teams.',
      businessImpact: 'Manufacturing sector faces near-term automation wave — BMW partnership signals enterprise validation of humanoid ROI.',
      impactScore: 84,
      metaTitle: 'Figure 02 Achieves 95% Factory Task Success with OpenAI | AI Pulse',
      metaDescription: 'Figure\'s humanoid robot hits 95% assembly task success at BMW using GPT-4o-powered VLA model. Robotics inflection point analysis.',
      ogImageUrl: null,
      category: 'robotics',
      tags: ['robotics', 'figure', 'humanoid', 'manufacturing'],
      trendingScore: 78,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 19800, shareCount: 3600,
      createdAt: new Date(now.getTime() - 42 * 60 * 60 * 1000),
    },
    {
      slug: 'mistral-codestral-code-model',
      title: 'Mistral Releases Codestral 2.0: Fastest Code Model at GPT-4 Quality',
      punchyTitle: 'Codestral 2.0: GPT-4 Coding Quality at 10× Speed',
      originalUrl: 'https://mistral.ai/news/codestral-2',
      source: { name: 'Mistral AI', url: 'https://mistral.ai' },
      author: 'Mistral AI',
      publishedAt: new Date(now.getTime() - 50 * 60 * 60 * 1000),
      summary: 'Mistral releases Codestral 2.0 with GPT-4 level HumanEval scores at 10× faster inference speed, targeting production coding assistant deployments.',
      punchySummary: 'Codestral 2.0 matches GPT-4o on HumanEval (86%) while running at 2,000+ tokens/sec — making real-time code completion economically viable at scale.',
      keyInsights: ['86% on HumanEval — matches GPT-4o', '2,000+ tokens/sec on standard hardware', 'FIM (fill-in-middle) optimized for IDE autocomplete', 'Apache 2.0 — self-hostable without licensing fees'],
      powerQuote: 'Codestral 2.0 makes real-time, frontier-quality code completion economically viable for teams of any size.',
      tldr: 'Codestral 2.0 matches GPT-4 coding quality at 10× inference speed, enabling real-time AI autocomplete at production scale.',
      whyItMatters: 'The speed gap between open and proprietary models closes — teams can now self-host GPT-4 quality code completion.',
      developerImpact: 'Real-time FIM completion at GPT-4 quality eliminates the tradeoff between latency and capability in AI code editors.',
      businessImpact: null,
      impactScore: 78,
      metaTitle: 'Codestral 2.0: GPT-4 Code Quality at 10× Speed | AI Pulse',
      metaDescription: 'Mistral releases Codestral 2.0 matching GPT-4o HumanEval at 2000+ tokens/sec. Open-source code model analysis.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['mistral', 'codestral', 'coding', 'open-source'],
      trendingScore: 72,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 15600, shareCount: 2800,
      createdAt: new Date(now.getTime() - 50 * 60 * 60 * 1000),
    },
    {
      slug: 'sam-altman-agi-timeline-2026',
      title: 'Sam Altman Says AGI Could Arrive "Within a Few Thousand Days"',
      punchyTitle: 'Altman: AGI Is Closer Than Anyone Thinks',
      originalUrl: 'https://techcrunch.com/2026/01/altman-agi-timeline',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 55 * 60 * 60 * 1000),
      summary: 'OpenAI CEO Sam Altman reiterated his belief that artificial general intelligence could arrive within a few thousand days, potentially by 2028-2030.',
      punchySummary: 'Altman doubles down on his AGI timeline, citing o3\'s reasoning breakthroughs and GPT-5\'s emergent capabilities as evidence the curve is steeper than public consensus believes.',
      keyInsights: ['AGI defined as "system that can do most cognitive work better than most humans"', 'o3 benchmark results cited as inflection point evidence', 'OpenAI investing $100B+ in compute for AGI development', 'Altman expects economic disruption to precede AGI by 2-3 years'],
      powerQuote: 'The thing I\'m most confident about is that we\'re going to be surprised by how fast this moves.',
      tldr: 'Altman publicly commits to AGI within "a few thousand days," citing recent reasoning model breakthroughs as proof the trajectory is steeper than expected.',
      whyItMatters: 'When the CEO of the leading AI lab makes concrete timeline claims, it signals internal confidence — and shapes investor, regulatory, and competitive behavior globally.',
      developerImpact: 'Developers should assume the API capabilities they build on will fundamentally change within 2-3 years — architect for model upgrades.',
      businessImpact: 'Boards and C-suites need AI transformation roadmaps now — not in 5 years.',
      impactScore: 82,
      metaTitle: 'Sam Altman: AGI Within a Few Thousand Days | AI Pulse',
      metaDescription: 'OpenAI CEO Sam Altman says AGI could arrive by 2028-2030, citing reasoning model breakthroughs. Full analysis.',
      ogImageUrl: null,
      category: 'industry',
      tags: ['agi', 'openai', 'altman', 'timeline'],
      trendingScore: 80,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 31200, shareCount: 6100,
      createdAt: new Date(now.getTime() - 55 * 60 * 60 * 1000),
    },
    {
      slug: 'apple-on-device-llm-ios-19',
      title: 'Apple Embeds 8B Parameter LLM Directly Into iOS 19',
      punchyTitle: 'Apple\'s On-Device 8B LLM Makes Siri Actually Useful',
      originalUrl: 'https://www.theverge.com/apple-ios19-llm',
      source: sources[7],
      author: 'The Verge',
      publishedAt: new Date(now.getTime() - 60 * 60 * 60 * 1000),
      summary: 'Apple iOS 19 ships with an 8 billion parameter language model running entirely on-device, powering a completely rebuilt Siri with no cloud dependency for most tasks.',
      punchySummary: 'iOS 19\'s on-device 8B LLM runs in 4-bit quantized form using Apple Neural Engine — zero cloud calls for writing assistance, summarization, and most Siri queries.',
      keyInsights: ['8B param model quantized to ~4GB, runs on A17 Pro and later', 'Zero cloud dependency for core tasks — full privacy', 'Beats GPT-3.5 on most mobile use-case benchmarks', 'Processes 50 tokens/sec on iPhone 16 Pro Neural Engine'],
      powerQuote: 'For the first time, the smartest AI on your phone isn\'t in a data center — it\'s in your pocket.',
      tldr: 'iOS 19 ships an on-device 8B LLM that outperforms GPT-3.5 on mobile tasks with zero cloud dependency, fundamentally changing mobile AI privacy.',
      whyItMatters: 'One billion iPhone users get private, always-available AI — this shifts user expectations for all mobile apps and pressures Android to follow.',
      developerImpact: 'iOS 19 APIs expose the on-device LLM for third-party apps — developers can run inference for free with no API costs.',
      businessImpact: 'Enterprise iOS apps can now process sensitive data with AI on-device — eliminating data sovereignty concerns.',
      impactScore: 86,
      metaTitle: 'Apple iOS 19: 8B On-Device LLM Powers New Siri | AI Pulse',
      metaDescription: 'Apple embeds 8B parameter LLM in iOS 19, running fully on-device with no cloud. Analysis of capabilities and developer implications.',
      ogImageUrl: null,
      category: 'industry',
      tags: ['apple', 'ios', 'on-device', 'siri', 'llm'],
      trendingScore: 84,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 27800, shareCount: 5300,
      createdAt: new Date(now.getTime() - 60 * 60 * 60 * 1000),
    },
    {
      slug: 'microsoft-copilot-autonomous-agents-enterprise',
      title: 'Microsoft Copilot Studio Launches Fully Autonomous Enterprise Agents',
      punchyTitle: 'Microsoft\'s Copilot Agents Run Entire Business Workflows Autonomously',
      originalUrl: 'https://venturebeat.com/ai/microsoft-copilot-autonomous',
      source: sources[4],
      author: 'VentureBeat',
      publishedAt: new Date(now.getTime() - 66 * 60 * 60 * 1000),
      summary: 'Microsoft Copilot Studio now supports fully autonomous multi-agent workflows that can execute complex enterprise tasks across Teams, Outlook, SharePoint, and Dynamics 365.',
      punchySummary: 'Copilot agents can now autonomously handle procurement workflows, customer service escalations, and finance reconciliation — touching 10+ enterprise systems without human steps.',
      keyInsights: ['Agents run 24/7 across Teams, Outlook, SharePoint, Dynamics, SAP', 'Human-in-the-loop controls configurable per workflow step', 'Average 67% reduction in manual process steps in pilots', '300+ enterprise customers in early access report positive ROI in week 1'],
      powerQuote: 'We\'re not automating tasks anymore — we\'re automating entire job functions.',
      tldr: 'Microsoft Copilot Studio enables autonomous multi-system enterprise agents, with pilot customers reporting 67% reduction in manual steps.',
      whyItMatters: 'Microsoft\'s distribution advantage means these agents reach 400M+ enterprise Microsoft 365 users — the largest autonomous agent rollout in history.',
      developerImpact: 'Copilot Studio\'s low-code agent builder means non-developers can deploy autonomous workflows — reducing demand for custom integration work.',
      businessImpact: 'Enterprises can now automate end-to-end workflows that previously required custom RPA + manual steps — potential 30-50% cost reduction in back-office ops.',
      impactScore: 81,
      metaTitle: 'Microsoft Copilot Autonomous Enterprise Agents Launch | AI Pulse',
      metaDescription: 'Microsoft Copilot Studio launches fully autonomous multi-agent workflows across enterprise systems. 67% process reduction in pilots.',
      ogImageUrl: null,
      category: 'agents',
      tags: ['microsoft', 'copilot', 'agents', 'enterprise'],
      trendingScore: 77,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 20400, shareCount: 3900,
      createdAt: new Date(now.getTime() - 66 * 60 * 60 * 1000),
    },
    {
      slug: 'deepseek-r2-china-reasoning-model',
      title: 'DeepSeek R2 Matches o3 at 1/10th the Training Cost',
      punchyTitle: 'DeepSeek R2 Shocks AI World with Efficient Reasoning',
      originalUrl: 'https://techcrunch.com/2026/deepseek-r2',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 72 * 60 * 60 * 1000),
      summary: 'Chinese AI lab DeepSeek releases R2, a reasoning model that matches OpenAI o3 on AIME and MATH benchmarks while requiring only 1/10th the training compute.',
      punchySummary: 'DeepSeek R2 achieves 94.2% on AIME (vs o3\'s 96.7%) using a novel mixture-of-experts architecture trained for $6M — compared to estimates of $60M+ for o3.',
      keyInsights: ['94.2% AIME score — 1.5pts below o3 at 1/10th training cost', 'Novel MoE architecture activates only 22B of 236B parameters per token', 'MIT license — fully open weights released simultaneously', 'Runs on 4× H100s — accessible to most research labs'],
      powerQuote: 'DeepSeek R2 proves that the compute gap between US and China AI is closing faster than export controls can manage.',
      tldr: 'DeepSeek R2 nearly matches o3 reasoning at 10% training cost using open-weight MoE, threatening US AI compute advantage narrative.',
      whyItMatters: 'Proves frontier reasoning is achievable without massive compute — undermines the assumption that chip export controls can contain Chinese AI progress.',
      developerImpact: 'Open weights mean any team can fine-tune a near-o3 reasoning model — eliminates reliance on proprietary reasoning APIs.',
      businessImpact: 'Pricing pressure on OpenAI o3 and Claude reasoning APIs — DeepSeek R2 API is already 95% cheaper.',
      impactScore: 90,
      metaTitle: 'DeepSeek R2 Matches o3 at 1/10th Cost | AI Pulse',
      metaDescription: 'DeepSeek R2 achieves near-o3 reasoning performance with open weights and $6M training cost. Full technical analysis.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['deepseek', 'reasoning', 'china', 'open-source', 'moe'],
      trendingScore: 89,
      isNew: true, isTrending: true, isHot: true,
      viewCount: 38500, shareCount: 8200,
      createdAt: new Date(now.getTime() - 72 * 60 * 60 * 1000),
    },
    {
      slug: 'stanford-hai-ai-index-2026',
      title: 'Stanford HAI 2026 AI Index: AI Now Outperforms Humans on 8 of 10 Benchmarks',
      punchyTitle: 'AI Beats Humans on 80% of Standard Benchmarks — Stanford Report',
      originalUrl: 'https://www.technologyreview.com/stanford-hai-2026',
      source: sources[5],
      author: 'MIT Tech Review',
      publishedAt: new Date(now.getTime() - 80 * 60 * 60 * 1000),
      summary: 'Stanford\'s annual AI Index report shows AI systems now outperform human baselines on 8 of 10 standard benchmarks, up from 5 of 10 in 2024.',
      punchySummary: 'AI exceeds human performance on reading comprehension, math, coding, image classification, and 4 more benchmarks — but still fails at long-horizon planning and novel physical reasoning.',
      keyInsights: ['AI surpasses humans on 8/10 benchmarks — up from 5/10 in 2024', 'Global AI investment hit $612B in 2025 — 3× over 2023', '40% of Fortune 500 now have AI in production core systems', 'AI-generated content accounts for 12% of all internet text'],
      powerQuote: 'The question is no longer whether AI can match human performance — it\'s which human tasks remain uniquely human.',
      tldr: 'Stanford\'s 2026 AI Index shows AI outperforms humans on 80% of standard benchmarks, with global investment tripling in 2 years.',
      whyItMatters: 'Annual tracking by a credible academic institution provides the clearest signal of how fast the capability frontier is moving.',
      developerImpact: null,
      businessImpact: 'Companies not deploying AI in core workflows are now at a measurable competitive disadvantage — the window for "wait and see" has closed.',
      impactScore: 76,
      metaTitle: 'Stanford AI Index 2026: AI Beats Humans on 80% of Benchmarks | AI Pulse',
      metaDescription: 'Stanford HAI 2026 report: AI outperforms humans on 8 of 10 benchmarks. $612B global investment. Full breakdown.',
      ogImageUrl: null,
      category: 'research',
      tags: ['stanford', 'research', 'benchmarks', 'report'],
      trendingScore: 74,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 17200, shareCount: 4100,
      createdAt: new Date(now.getTime() - 80 * 60 * 60 * 1000),
    },
    {
      slug: 'perplexity-ai-funding-series-e',
      title: 'Perplexity AI Raises $500M Series E at $14B Valuation',
      punchyTitle: 'Perplexity Hits $14B — AI Search Is a Real Market',
      originalUrl: 'https://techcrunch.com/2026/perplexity-series-e',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 90 * 60 * 60 * 1000),
      summary: 'Perplexity AI closes a $500M Series E at a $14 billion valuation, with SoftBank leading and Sony and NVIDIA participating, as the AI search company reaches 100M monthly users.',
      punchySummary: 'Perplexity at $14B valuation and 100M MAUs signals the AI search market is real — the company now processes more queries than Bing in the 18-34 demographic.',
      keyInsights: ['$14B valuation — 6× increase from Series D 18 months ago', '100M monthly active users — primarily 18-34 demographic', 'Outprocesses Bing in 18-34 age group', 'Revenue run rate of $120M ARR, targeting profitability by Q4 2026'],
      powerQuote: 'Perplexity is the first credible threat to Google Search since Google launched.',
      tldr: 'Perplexity raises $500M at $14B valuation with 100M users, proving AI-native search is a viable multi-billion dollar market.',
      whyItMatters: 'Validates that AI-native search can capture mainstream users — puts enormous pressure on Google to accelerate AI Overview and SGE rollouts.',
      developerImpact: 'Perplexity\'s API is now a serious alternative to web search APIs for building AI assistants that need real-time information.',
      businessImpact: 'Advertisers need AI search strategies now — traditional SEO alone no longer guarantees discovery.',
      impactScore: 78,
      metaTitle: 'Perplexity AI Raises $500M at $14B Valuation | AI Pulse',
      metaDescription: 'Perplexity AI closes $500M Series E at $14B with 100M monthly users. AI search market validation analysis.',
      ogImageUrl: null,
      category: 'industry',
      tags: ['perplexity', 'funding', 'search', 'startup'],
      trendingScore: 75,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 19600, shareCount: 3700,
      createdAt: new Date(now.getTime() - 90 * 60 * 60 * 1000),
    },
    {
      slug: 'google-alphafold-3-drug-discovery',
      title: 'Google AlphaFold 3 Predicts Drug-Protein Interactions With 94% Accuracy',
      punchyTitle: 'AlphaFold 3 Compresses 10 Years of Drug Discovery Into Months',
      originalUrl: 'https://deepmind.google/blog/alphafold-3-drug-discovery',
      source: sources[2],
      author: 'Google DeepMind',
      publishedAt: new Date(now.getTime() - 96 * 60 * 60 * 1000),
      summary: 'DeepMind releases AlphaFold 3 with the ability to predict drug-protein binding interactions at 94% accuracy, enabling pharmaceutical companies to screen billions of compounds computationally.',
      punchySummary: 'AlphaFold 3 predicts how any drug molecule binds to any protein target at 94% accuracy — enabling virtual screening of 10B+ compounds in weeks instead of decades of wet-lab work.',
      keyInsights: ['94% accuracy on drug-protein interaction prediction (vs 67% for AlphaFold 2)', 'Screens 10 billion compound-protein pairs per week on TPU clusters', '3 major pharma companies already using for active drug programs', 'Open access via API for academic and non-commercial use'],
      powerQuote: 'AlphaFold 3 doesn\'t just predict protein structures — it predicts the future of medicine.',
      tldr: 'AlphaFold 3 achieves 94% drug-protein binding accuracy, enabling pharma to virtually screen billions of compounds and compress drug discovery timelines.',
      whyItMatters: 'Computational drug discovery at this accuracy level could cut the average 12-year drug development timeline to 3-5 years for structure-based targets.',
      developerImpact: 'Free API for researchers opens AlphaFold 3 to academic labs globally — democratizing capabilities previously only available to top pharma.',
      businessImpact: 'Biotech and pharma companies that integrate AlphaFold 3 into pipelines gain 5-10× speed advantage in early discovery phases.',
      impactScore: 88,
      metaTitle: 'AlphaFold 3: 94% Drug-Protein Accuracy, Revolutionizes Discovery | AI Pulse',
      metaDescription: 'Google DeepMind\'s AlphaFold 3 predicts drug-protein interactions at 94% accuracy. Pharmaceutical AI revolution analysis.',
      ogImageUrl: null,
      category: 'research',
      tags: ['alphafold', 'deepmind', 'drug-discovery', 'biology'],
      trendingScore: 83,
      isNew: false, isTrending: true, isHot: false,
      viewCount: 23400, shareCount: 5100,
      createdAt: new Date(now.getTime() - 96 * 60 * 60 * 1000),
    },
    {
      slug: 'openai-realtime-api-voice-developers',
      title: 'OpenAI Realtime API Goes GA: Sub-300ms Voice AI for Any App',
      punchyTitle: 'OpenAI Realtime API: Build Voice AI With 300ms Latency',
      originalUrl: 'https://openai.com/blog/realtime-api-ga',
      source: sources[0],
      author: 'OpenAI',
      publishedAt: new Date(now.getTime() - 104 * 60 * 60 * 1000),
      summary: 'OpenAI\'s Realtime API reaches general availability, enabling developers to build voice-based AI applications with sub-300ms latency and native speech-to-speech processing.',
      punchySummary: 'The Realtime API GA enables any developer to build voice AI with 300ms end-to-end latency, native interruption handling, and emotion-aware responses — no separate TTS/STT needed.',
      keyInsights: ['Sub-300ms end-to-end voice latency — comparable to human conversation', 'Native speech-to-speech — no TTS/STT intermediary', 'Emotion and tone detection built in', '$0.06/min pricing — 40% cheaper than beta'],
      powerQuote: 'Building a voice AI app now takes an afternoon, not six months.',
      tldr: 'OpenAI Realtime API GA enables sub-300ms voice AI at $0.06/min with native speech-to-speech, emotion detection, and interruption handling.',
      whyItMatters: 'Drops the barrier to building voice AI to near-zero — expect an explosion of voice-native applications in healthcare, customer service, and consumer apps.',
      developerImpact: 'Voice AI prototyping goes from weeks to hours — WebSocket API with simple JSON protocol, full SDK support.',
      businessImpact: 'Call center AI deployments become economically viable at scale — $0.06/min vs $15-25/hour for human agents.',
      impactScore: 80,
      metaTitle: 'OpenAI Realtime API GA: 300ms Voice AI for Developers | AI Pulse',
      metaDescription: 'OpenAI Realtime API goes GA with sub-300ms latency voice AI at $0.06/min. Developer guide and business implications.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['openai', 'voice', 'api', 'realtime', 'developers'],
      trendingScore: 76,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 18900, shareCount: 3400,
      createdAt: new Date(now.getTime() - 104 * 60 * 60 * 1000),
    },
    {
      slug: 'tesla-optimus-gen3-factory-deployment',
      title: 'Tesla Deploys 1,000 Optimus Gen 3 Robots Across Fremont Factory',
      punchyTitle: 'Tesla\'s 1,000-Robot Optimus Army Begins Factory Work',
      originalUrl: 'https://venturebeat.com/ai/tesla-optimus-gen3-factory',
      source: sources[4],
      author: 'VentureBeat',
      publishedAt: new Date(now.getTime() - 110 * 60 * 60 * 1000),
      summary: 'Tesla begins full-scale deployment of 1,000 Optimus Gen 3 humanoid robots at its Fremont factory, handling battery module assembly and quality inspection tasks.',
      punchySummary: 'Tesla\'s 1,000-unit Optimus Gen 3 deployment handles battery module assembly at 92% accuracy — Musk projects 1M+ robots in Tesla factories by end of 2027.',
      keyInsights: ['1,000 units now operational at Fremont — largest humanoid deployment ever', '92% task success on battery module assembly', 'Trained using Tesla\'s full self-driving neural net architecture', 'Cost target: $20,000/unit by 2027 (vs $500K+ for current industrial robots)'],
      powerQuote: 'Optimus will be the most valuable product in Tesla\'s history — more valuable than all cars combined.',
      tldr: 'Tesla deploys 1,000 Optimus Gen 3 robots at Fremont with 92% task accuracy, targeting 1M units in factories by 2027.',
      whyItMatters: 'Tesla\'s manufacturing scale and vertical integration gives it a path to $20K humanoid robots — 25× cheaper than current alternatives.',
      developerImpact: null,
      businessImpact: 'Manufacturing companies should begin humanoid robot pilot planning — Tesla\'s cost curve suggests economic viability for broad industry by 2028.',
      impactScore: 83,
      metaTitle: 'Tesla Deploys 1,000 Optimus Gen 3 Robots at Fremont | AI Pulse',
      metaDescription: 'Tesla\'s 1,000 Optimus Gen 3 humanoid robots begin factory work at 92% accuracy. Robotics deployment analysis.',
      ogImageUrl: null,
      category: 'robotics',
      tags: ['tesla', 'optimus', 'robotics', 'humanoid', 'manufacturing'],
      trendingScore: 79,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 21700, shareCount: 4400,
      createdAt: new Date(now.getTime() - 110 * 60 * 60 * 1000),
    },
    {
      slug: 'amd-mi350-ai-chip-nvidia-competitor',
      title: 'AMD MI350 Challenges NVIDIA H200 with 2.3× Memory Bandwidth',
      punchyTitle: 'AMD MI350 Closes the Gap with NVIDIA on AI Training',
      originalUrl: 'https://techcrunch.com/2026/amd-mi350-launch',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 118 * 60 * 60 * 1000),
      summary: 'AMD launches the MI350 AI accelerator with 2.3× the memory bandwidth of NVIDIA H200 and competitive training throughput, backed by ROCm 7.0 software improvements.',
      punchySummary: 'MI350 delivers 2.3× H200 memory bandwidth and within 15% of H200 training throughput — combined with 30% lower pricing, AMD now has a viable enterprise AI chip offering.',
      keyInsights: ['2.3× memory bandwidth vs H200 — critical for large model inference', 'Within 15% of H200 on LLM training throughput', '30% lower list price than equivalent H200 configurations', 'ROCm 7.0 now supports 95% of PyTorch ops natively'],
      powerQuote: 'MI350 is the first AMD chip where switching from NVIDIA requires real trade-offs rather than sacrifices.',
      tldr: 'AMD MI350 offers 2.3× H200 memory bandwidth at 30% lower cost, with ROCm 7.0 closing the software gap — a credible NVIDIA alternative emerges.',
      whyItMatters: 'NVIDIA has had effective monopoly pricing on AI chips — AMD closing the gap creates genuine competition and should drive prices down 20-30%.',
      developerImpact: 'ROCm 7.0\'s improved PyTorch compatibility means most training code runs unchanged on AMD — switching costs drop significantly.',
      businessImpact: 'Data centers and cloud providers now have negotiating leverage with NVIDIA — expect AMD to capture 15-20% of AI chip market by 2027.',
      impactScore: 77,
      metaTitle: 'AMD MI350: 2.3× H200 Memory, 30% Cheaper AI Chip | AI Pulse',
      metaDescription: 'AMD MI350 challenges NVIDIA H200 with superior memory bandwidth and 30% lower cost. AI chip competition analysis.',
      ogImageUrl: null,
      category: 'chips',
      tags: ['amd', 'mi350', 'gpu', 'nvidia', 'chips'],
      trendingScore: 73,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 16800, shareCount: 3200,
      createdAt: new Date(now.getTime() - 118 * 60 * 60 * 1000),
    },
    {
      slug: 'hugging-face-smollm3-efficient-edge',
      title: 'Hugging Face SmolLM3 Sets New Edge AI Efficiency Record',
      punchyTitle: 'SmolLM3: GPT-3.5 Quality in a 3B Model That Runs on a Phone',
      originalUrl: 'https://huggingface.co/blog/smollm3',
      source: sources[6],
      author: 'Hugging Face',
      publishedAt: new Date(now.getTime() - 126 * 60 * 60 * 1000),
      summary: 'Hugging Face releases SmolLM3, a 3 billion parameter model that achieves GPT-3.5 quality on key benchmarks while running in real-time on mobile devices and edge hardware.',
      punchySummary: 'SmolLM3 scores within 2% of GPT-3.5 on MMLU and HumanEval while running at 40 tokens/sec on a Snapdragon 8 Gen 3 — the best quality/size ratio in open-source AI.',
      keyInsights: ['Within 2% of GPT-3.5 on MMLU and HumanEval at 3B params', '40 tokens/sec on Snapdragon 8 Gen 3 (flagship Android)', 'Apache 2.0 — commercial use allowed', 'Trained on 1T tokens using a novel data curriculum'],
      powerQuote: 'SmolLM3 is the model that makes AI ubiquitous — it runs anywhere, costs nothing, and is good enough for most real tasks.',
      tldr: 'SmolLM3 achieves near-GPT-3.5 quality at 3B parameters, running in real-time on mobile — the benchmark for efficient edge AI.',
      whyItMatters: 'Models this good at this size mean AI can run offline on any device globally — no internet, no API costs, no privacy concerns.',
      developerImpact: 'Mobile developers can ship on-device AI features with GPT-3.5 quality — no cloud costs, no latency, works offline.',
      businessImpact: null,
      impactScore: 74,
      metaTitle: 'SmolLM3: GPT-3.5 Quality at 3B Params, Runs on Mobile | AI Pulse',
      metaDescription: 'Hugging Face SmolLM3 achieves near-GPT-3.5 quality in 3B parameters running on mobile devices. Edge AI benchmark.',
      ogImageUrl: null,
      category: 'ml',
      tags: ['huggingface', 'smollm', 'edge-ai', 'mobile', 'efficient'],
      trendingScore: 70,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 14200, shareCount: 2600,
      createdAt: new Date(now.getTime() - 126 * 60 * 60 * 1000),
    },
    {
      slug: 'us-ai-safety-institute-standards-2026',
      title: 'US AI Safety Institute Releases Mandatory Testing Standards for Frontier Models',
      punchyTitle: 'US Makes Pre-Deployment Safety Testing Mandatory for Frontier AI',
      originalUrl: 'https://www.technologyreview.com/us-aisi-standards-2026',
      source: sources[5],
      author: 'MIT Tech Review',
      publishedAt: new Date(now.getTime() - 134 * 60 * 60 * 1000),
      summary: 'The US AI Safety Institute publishes mandatory pre-deployment testing standards for frontier AI models, requiring labs to complete red-teaming and capability evaluations before release.',
      punchySummary: 'All frontier AI models above a compute threshold must now pass AISI\'s mandatory safety evaluations — including bio, cyber, and CBRN risk assessments — before US deployment.',
      keyInsights: ['Mandatory for models above 10^26 FLOPs training compute', 'Evaluations cover bio, cyber, CBRN, and deceptive alignment risks', '90-day pre-deployment review window required', 'Labs must share model weights with AISI for evaluation'],
      powerQuote: 'This is the moment AI regulation in the US moved from voluntary to mandatory.',
      tldr: 'US AISI makes pre-deployment safety testing mandatory for frontier models, requiring 90-day reviews covering bio, cyber, and alignment risks.',
      whyItMatters: 'The first mandatory US AI regulation creates compliance requirements for every major AI lab — and sets a global precedent others will follow.',
      developerImpact: null,
      businessImpact: 'AI labs need dedicated safety teams and evaluation infrastructure — adds 3-6 months to product timelines for frontier models.',
      impactScore: 80,
      metaTitle: 'US AI Safety Institute Makes Frontier AI Testing Mandatory | AI Pulse',
      metaDescription: 'US AISI releases mandatory pre-deployment safety standards for frontier AI. 90-day review requirement, bio/cyber evaluations.',
      ogImageUrl: null,
      category: 'regulation',
      tags: ['regulation', 'safety', 'aisi', 'us-policy', 'frontier-ai'],
      trendingScore: 71,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 13800, shareCount: 2900,
      createdAt: new Date(now.getTime() - 134 * 60 * 60 * 1000),
    },
    {
      slug: 'cursor-ai-ide-10m-developers',
      title: 'Cursor Reaches 10M Developers — AI-Native IDEs Go Mainstream',
      punchyTitle: 'Cursor Hits 10M Devs: AI Coding Tools Are the New Standard',
      originalUrl: 'https://venturebeat.com/ai/cursor-10m-developers',
      source: sources[4],
      author: 'VentureBeat',
      publishedAt: new Date(now.getTime() - 140 * 60 * 60 * 1000),
      summary: 'Cursor announces 10 million active developers on its AI-native IDE, with enterprise ARR crossing $200M as major tech companies standardize on AI-assisted development workflows.',
      punchySummary: 'Cursor\'s 10M developer milestone and $200M ARR confirm AI-native IDEs have crossed the chasm — GitHub\'s own data shows AI-assisted code now accounts for 46% of all commits.',
      keyInsights: ['10M active developers — 5× growth in 12 months', '$200M ARR — profitable at current scale', 'Enterprise tier adopted by 15 of Fortune 100', 'GitHub data: 46% of all commits now AI-assisted'],
      powerQuote: 'In 3 years, writing code without AI assistance will feel like writing without spell-check.',
      tldr: 'Cursor reaches 10M developers and $200M ARR, confirming AI-native coding tools have gone mainstream with 46% of commits now AI-assisted.',
      whyItMatters: 'AI-assisted coding is no longer an experiment — it\'s standard practice, fundamentally changing hiring, productivity metrics, and software economics.',
      developerImpact: 'Developers not using AI coding tools are now measurably slower — industry surveys show 35-55% productivity gains for regular AI coding tool users.',
      businessImpact: 'Engineering teams can ship features 40% faster with the same headcount — AI coding tools have become a core productivity infrastructure.',
      impactScore: 75,
      metaTitle: 'Cursor Reaches 10M Developers: AI IDEs Go Mainstream | AI Pulse',
      metaDescription: 'Cursor hits 10M developers and $200M ARR. 46% of GitHub commits now AI-assisted. AI coding tool analysis.',
      ogImageUrl: null,
      category: 'industry',
      tags: ['cursor', 'coding', 'ide', 'developer-tools', 'ai-coding'],
      trendingScore: 73,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 16500, shareCount: 3800,
      createdAt: new Date(now.getTime() - 140 * 60 * 60 * 1000),
    },
    {
      slug: 'waymo-robotaxi-25-cities-expansion',
      title: 'Waymo Expands to 25 Cities After Recording Zero At-Fault Accidents in 5M Rides',
      punchyTitle: 'Waymo: Zero At-Fault Accidents in 5M Rides, Expanding to 25 Cities',
      originalUrl: 'https://techcrunch.com/2026/waymo-25-cities',
      source: sources[3],
      author: 'TechCrunch',
      publishedAt: new Date(now.getTime() - 148 * 60 * 60 * 1000),
      summary: 'Waymo announces expansion to 25 US cities after its safety report shows zero at-fault accidents across 5 million fully autonomous rides, establishing a clear lead in commercial robotaxi operations.',
      punchySummary: 'Waymo\'s 5M ride safety report shows 6.7× fewer injury-causing accidents than human drivers — now expanding to 25 cities with 1,500 vehicles, on track for profitability by 2027.',
      keyInsights: ['Zero at-fault accidents in 5M commercial rides', '6.7× safer than human drivers on injury-causing accidents', 'Expanding from 5 to 25 cities in 2026', '1,500 vehicle fleet with profitability target Q3 2027'],
      powerQuote: 'The data is clear — autonomous vehicles are safer than human drivers. The question is no longer if, but when.',
      tldr: 'Waymo\'s safety data across 5M rides shows 6.7× fewer injury accidents than humans, enabling 25-city expansion as commercial robotaxi becomes viable.',
      whyItMatters: 'Statistically significant safety data at commercial scale removes the key regulatory and public trust barrier to autonomous vehicle deployment.',
      developerImpact: null,
      businessImpact: 'Ride-sharing economics shift — Waymo\'s unit economics at 60% lower cost per mile than human-driven alternatives threaten Uber and Lyft\'s core business.',
      impactScore: 79,
      metaTitle: 'Waymo: Zero At-Fault Accidents in 5M Rides, Expanding to 25 Cities | AI Pulse',
      metaDescription: 'Waymo\'s safety report shows 6.7× fewer accidents than human drivers in 5M rides. 25-city robotaxi expansion analysis.',
      ogImageUrl: null,
      category: 'robotics',
      tags: ['waymo', 'autonomous-vehicles', 'robotaxi', 'safety'],
      trendingScore: 76,
      isNew: false, isTrending: false, isHot: false,
      viewCount: 19300, shareCount: 3600,
      createdAt: new Date(now.getTime() - 148 * 60 * 60 * 1000),
    },
  ]

  return articles.map((a, i) => ({ ...a, id: `mock-${i + 1}` })) as Article[]
}
